### ISSUE TITLE
4.27 Support

### ISSUE THREAD

**Issue by OwenCampos03** [modio/modio-ue4#3]
Please add real support for 4.27. I get BP compile errors every time I close and reopen my project (even though it compiled just fine before closing the editor), and I have to manually replace every single node used from the plugin in the BP (which is very time consuming to say the least).
Even if it gives me a prompt that says it was made for 4.26, I can still load the plugin into my project with no problem, but the errors only came up when I updated to the most recent version of the plugin.

**Comment by stephenwhittle** [comment]
Please provide a self-contained sample project demonstrating the issues you're having, or at least the output logs from the Blueprint compiler with the errors you're experiencing.
 
We have at least one studio about to ship a 4.27 update with the latest release of the Plugin here, and I just ran an additional test locally, upgrading to the latest Plugin release in a 4.27 project which did not require me to replace or upgrade any Plugin nodes, so I cannot reproduce your issue on the basis of the information provided so far. 

If you'd prefer to provide logs or a repro project privately, please either post in the #unreal channel in our public Discord at https://discord.gg/ZSqg2CSyxV so we can create a support ticket, or send an email to `support@mod.io`.

**Comment by OwenCampos03** [comment]
Well, if a version for 4.27 is about to be released, I can easily just wait until then. Thanks for the reply!

**Comment by stephenwhittle** [comment]
Sorry, to clarify: I mean that this release is confirmed to be working in 4.27, both internally and with external studios, one of whom is about to ship with it. 
If it isn't working for you, we'd definitely like to get to the bottom of why, if you can provide a repro project if possible, or the logs at least if that isn't feasible :)

**Comment by OwenCampos03** [comment]
Oh, I see! Yeah, it’s weird. This issue hasn’t come up for me in any previous version of the plugin, so I’m not sure why this would be happening. I’ll definitely try and replicate this in a separate project, so I’ll get back to you as soon as I do that.

**Comment by OwenCampos03** [comment]
Ok, so this is the type of error I'm getting.
![image](https://user-images.githubusercontent.com/60369817/187095733-b239f56a-75c3-4fc3-bf84-2143d596fae0.png)
This happens every time I reopen the project, and oddly enough, this error doesn't occur when I try using the plugin in a dummy project. I'm not sure if there's another plugin that's messing with it or what, but it's only happening in my main project.

**Comment by OwenCampos03** [comment]
It shows this same error when I disable the plugin, so it's like the project is just forgetting it even exists

**Comment by stephenwhittle** [comment]
Right. Could you try removing this line from Modio.uplugin:
`"EngineVersion": "4.26.0",`
Then do a full rebuild and post your build log if the errors persist?
It looks like your project isn't compiling the mod.io plugin for some reason, which is why it's giving errors as though you'd disabled it entirely.

**Comment by OwenCampos03** [comment]
The problem is still persisting unfortunately.
Here's the output log:
[Compile Log 8-28-2022.txt](https://github.com/modio/modio-ue4/files/9441327/Compile.Log.8-28-2022.txt)

**Comment by stephenwhittle** [comment]
There's a series of errors there relating to non-mod.io code that may be causing you problems: 
```
LogCompile: Error: Circular dependency detected for filename C:\Users\Owner\Unreal Projects\YourBrce\[project name]\Objects\InteractableObject.h!
LogCompile: Error: Circular dependency detected for filename C:\Users\Owner\Unreal Projects\YourBrce\[project name]\RoomGeneration\Room.h!
LogCompile: Error: Circular dependency detected for filename C:\Users\Owner\Unreal Projects\YourBrce\[project name]\RoomGeneration\RoomSpawnComponent.h!
```

Could you please address these and if the issue persists provide a fresh log after that?

**Comment by OwenCampos03** [comment]
Ok, I've fixed those errors now
Here's the new log:
[Compiler Log 8-29-2022.txt](https://github.com/modio/modio-ue4/files/9446763/Compiler.Log.8-29-2022.txt)

**Comment by OwenCampos03** [comment]
Ok, here's the startup log
[8-31-2022.log](https://github.com/modio/modio-ue4/files/9463320/8-31-2022.log)

**Comment by stephenwhittle** [comment]
So the plugin is mounting without error:
`LogPluginManager: Mounting plugin modio`

And it is being loaded without error as well:
`[2022.08.31-16.34.52:572][  0]LogModio: Display: Setting log level to 1`

However, your assets aren't being loaded properly by the linker:
`[2022.08.31-16.34.50:880][  0]LogLinker: Warning: [AssetLog] C:\Users\Owner\Unreal Projects\YourBackrooms\Content\FirstPerson\Animations\Player_Hands_AnimBP.uasset: Failed to load '/Script/Modio': Can't find file.`

This error isn't happening with any of our assets though, so, especially given that you mentioned that the plugin works fine in another project, this seems like something specific to your environment or project rather than something broken in the Plugin. 

I do note that the plugin name is 'modio' above - did you originally install it as 'Modio' ? In theory this shouldn't be case-sensitive but please try renaming the plugin folder and seeing if that helps. 

Double-check that your uproject file includes the plugin - this should already be there if you were using the previous version without issues. 

You could also try adding 'Modio' to your PrivateDependencyModuleNames entry in your project module's build.cs file if you have one. Again, this shouldn't be necessary if you were already using a previous iteration of the plugin, but it's something to test.

At this point, if refreshing the nodes in your blueprints doesn't make the error go away, I'd ask that you provide a copy of the project as mentioned above - whilst this isn't a Plugin issue, the team can take a quick look and may be able to identify what the problem is as a result of loading it ourselves.

**Comment by OwenCampos03** [comment]
Ok, so I looked into the "Script" folder in my project, and there's literally nothing there. I figure this is the issue, since it's looking for a file in that folder when there's literally nothing in it.

**Comment by OwenCampos03** [comment]
Ok, so after deleting the "Script" folder completely, the log shows a lot of messages about something "not being initialized":
[YourBackrooms.log](https://github.com/modio/modio-ue4/files/9472616/YourBackrooms.log)

**Comment by stephenwhittle** [comment]
In this instance, `/Script/Modio` is a virtual path for all the Modio plugin's C++ classes rather than referring to a physical folder on your machine. As an example, there are other references to `/Script/` in your log, such as `/Script/CustomGravityPlugin.Default__PlanetActor:SphereCollision0` which is clearly not a file path. 

The messages you were getting about things 'not being initialized' refers to the lack of default initializer values in the structs, which is in this instance an irrelevant warning that occurs in my own test project as well (Epic added a warning for it in 4.27). Those messages were present in your earlier logs, and also include warnings for other plugins that you're using, and haven't occurred as a result of deleting the Script folder you found. 

Please try the above suggestions after reverting the deletion.

**Comment by OwenCampos03** [comment]
Oh, ok. Yeah the error doesn't go away no matter what I do. Even after doing all of what you suggested, it still gives me the error.
How should I send the project to you? I haven't done something like this with GitHub before, so I'm not sure what to do besides add you as a collaborator or something.

**Comment by stephenwhittle** [comment]
Best bet would be to archive your project up and send an email to support@mod.io with a link :)

**Comment by OwenCampos03** [comment]
Alright, sending it now

**Comment by OwenCampos03** [comment]
So... any luck?

**Comment by stephenwhittle** [comment]
Sorry, it looks like your original email got caught up in a spam filter. 
I have downloaded the project, and after installing some of the plugins you're using (and disabling AutoSettings, because it's a commercial plugin and I don't have access to it), I can load the editor just fine.
![image](https://user-images.githubusercontent.com/7070635/191871065-c68df9cd-0c8a-4108-aa09-22a56c323423.png)

As a result this issue must be being caused by something broken in your local environment. 
I do note that your .uproject references the modio Marketplace plugin, but you've got the plugin in the folder here as well. I suspect the version you have installed via the Launcher may be causing issues with the version you've placed into your project.
 Could I suggest that you 
a) remove the mod.io plugin from your Unreal installation via the launcher
if that fails to allow the project to compile and load without errors,
b) you may need to purge your local install of UE 4.27 and reinstall it.

**Comment by OwenCampos03** [comment]
Wow, would you look at that. Uninstalling and reinstalling 4.27 worked, and I can use the plugin properly. Thank you so much for the help!

**Comment by stephenwhittle** [comment]
Thanks for confirming this is resolved :)
